name: Secretlint and Yaml lint
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run_secretlint:
    name: Secretlint
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
      - name: run secretlint command on docker
        id: run-secretlint-command
        uses: addnab/docker-run-action@v3
        with:
          # https://hub.docker.com/r/secretlint/secretlint/tags
          image: secretlint/secretlint:v5.1.1
          # https://github.com/secretlint/secretlint#using-docker
          options: >
            -v ${{ github.workspace }}:${{ github.workspace }}
            -w=${{ github.workspace }}
            --rm
          #run: secretlint ${{ env.GIT_DIFF_FILTERED }} # run only on changed files
          run: secretlint "**/*" # run on all files under github.workspace directory
        if: env.GIT_DIFF && !env.MATCHED_FILES
